### ISSUE TITLE
Activate in NodeBB 1.16.x?

### ISSUE THREAD

**Issue by NormandoHall** [julianlam/nodebb-plugin-soundpack-default#5]
Hi @julianlam 

What happens if I activated this plugin in 1.16.x?

Thanks

**Comment by julianlam** [comment]
Since sounds have been removed, this plugin will do nothing in v1.16.x :smile:

**Comment by julianlam** [comment]
This plugin will need to be eventually updated to provide sounds directly. Right now it only provides sounds for core to consume, which it no longer does.

**Comment by NormandoHall** [comment]
> This plugin will need to be eventually updated to provide sounds directly. Right now it only provides sounds for core to consume, which it no longer does.

Right. I hope this can be made soon. I have no deep knowledge of NodeBB development to contribute. We really appreciate sounds notifications! :smile:  Thanks

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-soundpack-default/commit/e91b37a79b386c45395a4cd62ddf57520f39b6e3
